### ISSUE TITLE
Pressing Escape button does not toggle between Lighttable and Darkroom

### ISSUE THREAD

**Issue by charlyFromLypac** [aurelienpierreeng/ansel#198] opened 2023-08-02 14:00 UTC
## Description of the bug

The shortcut _Escape_ as visible in the Atelier menu does not switch between Lighttable and the Darkroom.

**To Reproduce**

1. Select photo and go to the darkroom via the menu attelier
2. Pres the _Escape_ button (for me it is the _Esc_ button tha could have another value if placed in the right left corner of keyboard?)
3. A message is displayed
4. Message: _Attelier/Lighttable not active_

## Expected behavior
Switching from Lighttable to Darkroon and vice versa.

**Screenshots**
NA

**Screencast**
```
Operating System: 19041.1.amd64fre.vb_release.191206-1406 10.0.0.0.2.101

Step 1: User left click on "Ansel (window)" in "Ansel"
Program: ansel photo workflow software, 26acfc2, The ansel team, ANSEL.EXE, ANSEL.EXE
UI Elements: Ansel, gdkWindowToplevel

Step 2: User left double click on "Ansel (window)" in "Ansel"
Program: ansel photo workflow software, 26acfc2, The ansel team, ANSEL.EXE, ANSEL.EXE
UI Elements: Ansel, gdkWindowToplevel

Step 3: User left click on "Ansel (window)" in "Ansel"
Program: ansel photo workflow software, 26acfc2, The ansel team, ANSEL.EXE, ANSEL.EXE
UI Elements: Ansel, gdkWindowToplevel

Step 4: User left click on "ansel.exe (pane)" in "ansel.exe"
Program: ansel photo workflow software, 26acfc2, The ansel team, ANSEL.EXE, ANSEL.EXE
UI Elements: ansel.exe, gdkWindowTemp, Ansel, gdkWindowToplevel

Step 5: User left click on "Ansel (window)" in "Ansel"
Program: ansel photo workflow software, 26acfc2, The ansel team, ANSEL.EXE, ANSEL.EXE
UI Elements: Ansel, gdkWindowToplevel

Step 6: User left click on "ansel.exe (pane)" in "ansel.exe"
Program: ansel photo workflow software, 26acfc2, The ansel team, ANSEL.EXE, ANSEL.EXE
UI Elements: ansel.exe, gdkWindowTemp, Ansel, gdkWindowToplevel

Step 7: User keyboard input on "Ansel (window)" in "Ansel" [ESC]
Program: ansel photo workflow software, 26acfc2, The ansel team, ANSEL.EXE, ANSEL.EXE
UI Elements: Ansel, gdkWindowToplevel

Step 8: User left click on "Ansel (window)" in "Ansel"
Program: ansel photo workflow software, 26acfc2, The ansel team, ANSEL.EXE, ANSEL.EXE
UI Elements: Ansel, gdkWindowToplevel

Step 9: User left click on "ansel.exe (pane)" in "ansel.exe"
Program: ansel photo workflow software, 26acfc2, The ansel team, ANSEL.EXE, ANSEL.EXE
UI Elements: ansel.exe, gdkWindowTemp, Ansel, gdkWindowToplevel

Step 10: User left click on "Ansel (window)" in "Ansel"
Program: ansel photo workflow software, 26acfc2, The ansel team, ANSEL.EXE, ANSEL.EXE
UI Elements: Ansel, gdkWindowToplevel

Step 11: User keyboard input on "Ansel (window)" in "Ansel" [ESC]
Program: ansel photo workflow software, 26acfc2, The ansel team, ANSEL.EXE, ANSEL.EXE
UI Elements: Ansel, gdkWindowToplevel
```

## Which commit introduced the error

NA

## System

* darktable version : ansel 26acfc2
* OS                : Win10 (Patchlevel)
* OSVersion                     : 2009
* OSEdition                     : Windows 10 Home
* OSBuild                       : 19045.3208
* CurrentInstalledUpdate        : July 11, 2023 - KB5028166 (OS Builds 19044.3208 and 19045.3208)
* CurrentInstalledUpdateKB      : KB5028166
* CurrentInstalledUpdateInfoURL : https://support.microsoft.com/en-us/help/5028166
* Linux - Distro    : NA
* Memory            : 16BG
* Graphics card     : 3050ti Nvidia and AMD Radeon on a Ryzen 7 cpu
* Graphics driver   : unknown
* OpenCL installed  : YES
* OpenCL activated  : YES
* Xorg              : NA
* Desktop           : NA
* GTK+              : unknown
* gcc               : unknown
* cflags            : unknown
* CMAKE_BUILD_TYPE  : unknown

**Additional context**

NA

**Comment by lukadh** [comment] 2023-08-02 19:37
Duplicate of #170 which was fixed by https://github.com/aurelienpierreeng/ansel/commit/dd3d7f559861115fa40f9c17b2c7a68ca4a508d3 

But it looks like you are on the latest Windows build available which was before this fix.

**Comment by lukadh** [comment] 2023-08-02 19:48
Ok, I just checked the Matrix chat and it seems there are no Windows builds because of #181 

"Current Windows build is broken since MingW64 has updated libxml2 to a newer version of the lib that deprecates the parser we use in the Lightroom XMP -> dt XMP conversion" Aurélien

**Comment by lukadh** [comment] 2023-08-02 20:11
So the easiest fix for the moment would be to add the missing shortcuts manually in the  _Edit > Key Shortcuts_ dialog. But I think that the action `global/Ateliers/Lighttable` would be missing in your version. 

So either you ou could try and use the import the _default shortcuts_ via _Edit > Key Shortcuts_ But I'm not sure if it's the same in Windows and it will probably overwrite all your custom shortcuts. 

[Ansel-shortcutsrc-defaults.zip](https://github.com/aurelienpierreeng/ansel/files/12244195/Ansel-shortcutsrc-defaults.zip)

Or otherwise If you are willing to edit the your shortcuts file manually, you could probably  locate your [configuration files](https://ansel.photos/en/doc/install/configuration/) and copy paste the missing line(s).

**Comment by charlyFromLypac** [comment] 2023-08-03 19:08
Hello,

The shortcuts are there in the files, checked all of them.

Probably I'm more missing the code or compiled code handling that.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by lukadh** [comment] 2023-08-03 20:47
Yes, sorry I wasn't really thinking. After I looked into what was actually fixed with https://github.com/aurelienpierreeng/ansel/commit/dd3d7f559861115fa40f9c17b2c7a68ca4a508d3 I realised that my last answer was none-sense and deleted it.

**Comment by pedrorrodriguez** [comment] 2023-08-06 15:42
May I close, @aurelienpierre ?

**Comment by aurelienpierre** [comment] 2023-08-28 11:59
> May I close, @aurelienpierre ?

Libxml2 issue is fixed now so Win build should resume to normal starting tonight around 1 AM UTC.

**Closed by aurelienpierre** 2023-08-28 11:59 UTC
Labels: duplicate
