### ISSUE TITLE
lua support

### ISSUE THREAD

**Issue by aadm** [aurelienpierreeng/ansel#50] opened 2022-12-19 22:57 UTC
ansel built from source, liblua 5.4 installed, lua support gets recognized and built-in during compile.

At first launch with brand new config lua support is present, I can install scripts no problem, but then at second launch the lua menu disappears. Lua support used to be working correctly until a few commits ago (mid-december I think, can't remember the commit id unfortunately).

**Comment by ptilopteri** [comment] 2022-12-20 04:20
saw a similar problem on dt, try:
change css, comment out the line
  font-feature-settings: "tnum";

**Comment by MaTeng211** [comment] 2022-12-20 17:32
I see same issue.
What css are you referring so I can give it a try?

**Comment by ptilopteri** [comment] 2022-12-20 20:27
* MaTeng211 ***@***.***> [12-20-22 12:34]:
> I see same issue.
> What css are you referring so I can give it a try?
> 


css which defines the theme for dt which is selected in preferences ->
general

font-feature-settings: "tnum";

add a # at the beginning of that line and you will display ok.


-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
http://en.opensuse.org    openSUSE Community Member    facebook/ptilopteri
Photos: http://wahoo.no-ip.org/piwigo                   paka @ IRCnet oftc

**Comment by MaTeng211** [comment] 2022-12-20 20:42
?? 
I assume you refer here for ansel to the file "/opt/ansel/share/darktable/themes/ansel.css"?
Here in my setup there is no such line with "font-feature-settings..." that I might comment in there...

**Comment by ptilopteri** [comment] 2022-12-20 23:49
* Alessandro Amato del Monte ***@***.***> [12-20-22 16:05]:
> I have also tried to look into all the css I could find and there isn't any reference to `font-feature-settings` that I can deactivate...

open dt/ansel access preferences (gear)
access general

lists your css settings for prefered display

if not there, you should be ok as you are not using it and it *was*
broken.

if your display is ok, do not worry about it!


-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
http://en.opensuse.org    openSUSE Community Member    facebook/ptilopteri
Photos: http://wahoo.no-ip.org/piwigo                   paka @ IRCnet oftc

**Comment by aadm** [comment] 2022-12-21 10:25
@ptilopteri thanks for the reply, I did look into the ansel.css as well as my custom css `~/.config./ansel/user.css` but there is no such line (`font-feature-settings`) and still I can't display the LUA tab in the bottom left which was the original problem. On dt I don't have the same issue (both compiled from recent master, so all libraries etc are the same).

**Comment by aurelienpierre** [comment] 2023-01-05 20:57
Reproduced.

**Comment by aurelienpierre** [comment] 2023-01-05 21:03
So the Lua script manager is installed in `.config/ansel/lua/tools/script_manager.lua` and looks for darktable binaries. Since it gets installed from `clone https://github.com/darktable-org/lua-scripts.git` directly, that needs forking too.

**Comment by aurelienpierre** [comment] 2023-12-12 20:44
Fixed with [2bbd3f7](https://github.com/aurelienpierreeng/ansel/commit/2bbd3f7c0040cce891bdc8cf5572a7856194140a)

**Closed by aurelienpierre** 2023-12-12 20:44 UTC
Labels: regression
