### ISSUE TITLE
Writing a "custom" XMP when outputting

### ISSUE THREAD

**Issue by RawConvert** [aurelienpierreeng/ansel#9] opened 2022-06-29 11:44 UTC
I like to be confident I have an XMP to match my output (eg jpeg) and not risk accidentally losing it by making further edits.
I always add some kind of subject words to my output file name. I make an XMP with exactly the same file name as the output, outside dt. How about having the option in dt to do this automatically? That is, no need to affect the current "default" XMP file name or its processing/usage. But in addition output an extra XMP named like the main output.  If it already exists, just overwrite it?
I guess it would be necessary to turn this on or off per user in Preferences or in the Output module.

**Comment by aurelienpierre** [comment] 2022-07-17 20:33
What about simply creating a duplicate of each of your editing versions ? You can duplicate any history stack and keep working on it further while not changing the original one, then assign the number ID of the duplicate to the output JPEG name, and done.

**Comment by RawConvert** [comment] 2022-07-19 21:45
AFAIK duplicates are based on a numeric suffix, whereas I'm after something using text, that is, I type in (add) a meaningful name for the jpeg output and would like a matching XMP.

**Comment by todd-prior** [comment] 2022-07-24 20:46
@RawConvert  you can just append version_name to your export and it will add the next that you assigned the duplicate....

**Comment by aurelienpierre** [comment] 2023-01-20 02:04
`$(version_name)` in the exported file will do it.

**Closed by aurelienpierre** 2023-01-20 02:04 UTC
