### ISSUE TITLE
Retouch module does not show/apply correction

### ISSUE THREAD

**Issue by vtyrtov** [aurelienpierreeng/ansel#311] opened 2024-01-04 16:53 UTC
The "Retouch" module does not display or apply corrections.

![image](https://github.com/aurelienpierreeng/ansel/assets/22073549/a033057a-f5eb-49dd-8683-2a5dce189cdd)
![image](https://github.com/aurelienpierreeng/ansel/assets/22073549/6cfd7c49-8664-467e-9ccc-1b9dd43add18)

The problem is reproduced starting from Ansel-ba4dc39-x86_64.AppImage by the current build.

The problem is relevant the first time shape is added to the module. When you reopen the image or add shapes, the problem goes away.

The console displays:
```
[_dev_add_history_item_ext] invalidating history
[_dev_add_history_item_ext] invalidating history
[_dev_add_history_item_ext] invalidating history
[_dev_add_history_item_ext] invalidating history
rt_process_forms: missing form=1704386040 from array
rt_process_forms: missing form=1704386040 from array
```
See src/iop/retouch.c:
```c
        const int index = rt_get_index_from_formid(p, formid);
        if(index == -1)
        {
          // FIXME: we get this error when user go back in history, so forms are the same but the array has changed
          fprintf(stderr, "rt_process_forms: missing form=%i from array\n", formid);
          continue;
        }
```

_Originally posted by @vtyrtov in https://github.com/aurelienpierreeng/ansel/issues/310#issuecomment-1877403103_

**Comment by aurelienpierre** [comment] 2024-01-04 19:49
Duplicate of #310

**Closed by aurelienpierre** 2024-01-04 19:49 UTC
