### ISSUE TITLE
Running appimage on NixOS fails with `Unable to load image-loading module: libpixbufloader-svg.so`

### ISSUE THREAD

**Issue by koiuo** [aurelienpierreeng/ansel#202] opened 2023-08-19 20:43 UTC
## Description of the bug

**To Reproduce**

```
$ rm -rf ~/.config/ansel
$ nix-shell -p appimage-run
(nix-shell)$ appimage-run Ansel-ff82b58-x86_64.AppImage

Ansel-ff82b58-x86_64.AppImage installed in /home/***/.cache/appimage-run/bf7c47636163d916a0adc66a3f48258df45413bb6594379a771891d1fe2c1ade
/home/***/.cache/appimage-run/bf7c47636163d916a0adc66a3f48258df45413bb6594379a771891d1fe2c1ade/AppRun.wrapped: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /home/***/.cache/appimage-run/bf7c47636163d916a0adc66a3f48258df45413bb6594379a771891d1fe2c1ade/usr/bin/../lib/libansel.so)
/home/***/.cache/appimage-run/bf7c47636163d916a0adc66a3f48258df45413bb6594379a771891d1fe2c1ade/AppRun.wrapped: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /home/***/.cache/appimage-run/bf7c47636163d916a0adc66a3f48258df45413bb6594379a771891d1fe2c1ade/usr/bin/../lib/libexiv2.so.27)
/home/***/.cache/appimage-run/bf7c47636163d916a0adc66a3f48258df45413bb6594379a771891d1fe2c1ade/AppRun.wrapped: /home/***/.cache/appimage-run/bf7c47636163d916a0adc66a3f48258df45413bb6594379a771891d1fe2c1ade/usr/bin/../lib/libjson-glib-1.0.so.0: no version information available (required by /nix/store/vbav9yp30z4yxcg60hp0ay5r9phbf4dl-tracker-3.5.1/lib/libtracker-sparql-3.0.so.0)
[l10n] error: can't open iso-codes file `/usr/share/iso-codes/json/iso_639-2.json'
       there won't be nicely translated language names in the preferences.
Gtk-Message: 22:36:10.164: Failed to load module "window-decorations-gtk-module"
Gtk-Message: 22:36:10.164: Failed to load module "colorreload-gtk-module"

(AppRun.wrapped:2): Gtk-WARNING **: 22:36:10.910: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /run/current-system/sw/share/icons/breeze/status/16/image-missing.svg: Unable to load image-loading module: libpixbufloader-svg.so: libpixbufloader-svg.so: cannot open shared object file: No such file or directory (gdk-pixbuf-error-quark, 5)
Bail out! Gtk:ERROR:../gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /run/current-system/sw/share/icons/breeze/status/16/image-missing.svg: Unable to load image-loading module: libpixbufloader-svg.so: libpixbufloader-svg.so: cannot open shared object file: No such file or directory (gdk-pixbuf-error-quark, 5)
```

## Expected behavior

AppImage should contain all the dependencies necessary to run the application. Quick seach showed `librsvg` may be missing.

I understand, NixOS support is outside of this project scope. But in case if it is an easy fix, it would be really welcome.

## System

* ansel version     : ff82b58
* OS                : Linux 6.4.4
* Linux - Distro    : NixOS

**Comment by TheSirC** [comment] 2023-08-20 16:51
I happen to be on NixOS and _if your only goal is to be able to run Ansel_, I made an [overlay](https://nixos.wiki/wiki/Overlays) like this that runs without any problems with https://github.com/NixOS/nixpkgs/commit/897876e4c484f1e8f92009fd11b7d988a121a4e7: 

```Nix
self: super: {
ansel = super.stdenv.mkDerivation rec {
  name = "ansel-git";

  src = super.lib.cleanSource (super.fetchFromGitHub {
    owner = "aurelienpierreeng";
    repo = "ansel";
    rev = "26acfc25137d264cd39efdccc3de99a24e746f3f";
    hash = "sha256-S3QF4/1Yu+CLF6f862ljxBXSzSH7mTE8M8JcyqfvWiw=";
    fetchSubmodules = true;
  });

  nativeBuildInputs = [ super.git ];

  buildInputs = with super; with super.xorg; with super.gnome2;
    [ atk cairo cmake curl dbus-glib exiv2 glib gtk3
      ilmbase intltool lcms2 lensfun libX11 libexif
      libjpeg libpng
      librsvg libtiff libxcb openexr pixman pkgconfig sqlite libxslt
      libsoup graphicsmagick json-glib openjpeg lua5_3 pugixml
      colord colord-gtk libxshmfence libxkbcommon at-spi2-core
      libwebp libsecret wrapGAppsHook gnome3.adwaita-icon-theme
      osm-gps-map
    ];

  cmakeFlags = [
    "-DBUILD_USERMANUAL=False"
  ];

  # ansel changed its rpath handling in commit
  # 83c70b876af6484506901e6b381304ae0d073d3c and as a result the
  # binaries can't find libansel.so, so change LD_LIBRARY_PATH in
  # the wrappers:
  preFixup = ''
    gappsWrapperArgs+=(
      --prefix LD_LIBRARY_PATH ":" "$out/lib/ansel"
    )
  '';

};
}
```

**Comment by koiuo** [comment] 2023-08-21 23:01
@TheSirC , thanks a lot!

I added `ocl-icd` to inputs and to `LD_LIBRARY_PATH` to enable open-cl support.

Do you plan to contribute this to nixpkgs?

```
self: super: {
ansel = super.stdenv.mkDerivation rec {
  name = "ansel-git";

  src = super.lib.cleanSource (super.fetchFromGitHub {
    owner = "aurelienpierreeng";
    repo = "ansel";
    rev = "26acfc25137d264cd39efdccc3de99a24e746f3f";
    hash = "sha256-S3QF4/1Yu+CLF6f862ljxBXSzSH7mTE8M8JcyqfvWiw=";
    fetchSubmodules = true;
  });

  nativeBuildInputs = [ super.git ];

  buildInputs = with super; with super.xorg; with super.gnome2;
    [ atk cairo cmake curl dbus-glib exiv2 glib gtk3
      ilmbase intltool lcms2 lensfun libX11 libexif
      libjpeg libpng
      librsvg libtiff libxcb openexr pixman pkgconfig sqlite libxslt
      libsoup graphicsmagick json-glib openjpeg lua5_3 pugixml
      colord colord-gtk libxshmfence libxkbcommon at-spi2-core
      libwebp libsecret wrapGAppsHook gnome3.adwaita-icon-theme
      osm-gps-map ocl-icd
    ];

  cmakeFlags = [
    "-DBUILD_USERMANUAL=False"
  ];

  # ansel changed its rpath handling in commit
  # 83c70b876af6484506901e6b381304ae0d073d3c and as a result the
  # binaries can't find libansel.so, so change LD_LIBRARY_PATH in
  # the wrappers:
  preFixup = ''
    gappsWrapperArgs+=(
      --prefix LD_LIBRARY_PATH ":" "$out/lib/ansel:${super.ocl-icd}/lib"
    )
  '';

};
}
```

**Comment by TheSirC** [comment] 2023-08-22 19:35
> I added `ocl-icd` to inputs and to `LD_LIBRARY_PATH` to enable open-cl support.

I remember trying to add it and having issues (did not leave notes anywhere about it sadly)... Glad it works for you ! :+1: 

> Do you plan to contribute this to nixpkgs?

I was unsure about being able to maintain it long-term but I was mainly waiting to see if it broke regularly to see if it was stable enough for nixpkgs.

**Comment by hyshka** [comment] 2023-11-26 00:16
Thanks for both of your references. I have a version of them running in a pkg format here: https://github.com/hyshka/nix-config/blob/main/pkgs/ansel/default.nix

Stability is currently unknown but it launches.

**Comment by aurelienpierre** [comment] 2024-01-02 02:08
I'm not sure what the issue is here. The AppImage is supposed to provide Gtk and all its dependencies. Your log shows that several are missings but also some conflicts with theme icons, which could be outside the app/AppImage. 

If you install them with your OS package manager, does it fix the issue ?

**Comment by aurelienpierre** [comment] 2024-06-04 18:38
Closing for lack of actionnable info.

**Closed by aurelienpierre** 2024-06-04 18:38 UTC
