### ISSUE TITLE
Unable to compile with AUR as well as compiling from sources

### ISSUE THREAD

**Issue by jparsert** [aurelienpierreeng/ansel#191] opened 2023-07-13 09:51 UTC
## Description of the bug
When installing with AUR (I'm on Manjaro) I get several compilation errors telling me that several types are not present in the Exiv2 namespace. Compiling from source leads to similar errors e.g.:

```
ansel/src/common/exif.cc:290:17: error: ‘AnyError’ in namespace ‘Exiv2’ does not name a type
...
`ansel/src/common/exif.cc:1424:29: error: ‘const class Exiv2::Exifdatum’ has no member named ‘toLong’
...
```

## System

* darktable version : latest commit on git
* OS                : 6.3.12-1-MANJARO
* Linux - Distro    : e.g. Manjaro
* Memory            :
* Graphics card     :
* Graphics driver   :
* OpenCL installed  :
* OpenCL activated  :
* Xorg              :
* Desktop           :
* GTK+              :
* gcc               : 13.1.1
* cflags            :
* CMAKE_BUILD_TYPE  : Release

**Additional context**

exiv2 version  0.28.0-3

**Comment by aurelienpierre** [comment] 2023-07-14 21:12
Duplicate of #172.

See #161.

**Closed by aurelienpierre** 2023-07-14 21:12 UTC
Labels: duplicate
