### ISSUE TITLE
Unable to apply style

### ISSUE THREAD

**Issue by kred** [aurelienpierreeng/ansel#263] opened 2023-12-10 10:25 UTC
## Description of the bug

Hi! Recent changes (55d8a7a build) broke applying style in Darkroom mode - in Lighttable it works OK. Previous builds (like from 3-4 days ago) were fine.

**To Reproduce**

1. Create style
2. Switch to Darkroom
3. Apply style
4. Application is not responsive
5. After restart, style is applied to photo, editing works fine

## Expected behavior

Style is correctly applied to photo in Darkroom.

## Context

**Screenshots**
My style:
![obraz](https://github.com/aurelienpierreeng/ansel/assets/2844056/857fcfa4-bcf8-4794-a68b-5890bfbb8a7b)

**Screencast**

## System

* darktable version : 55d8a7a 
* OS                : Win11
* Linux - Distro    : e.g. Ubuntu 18.4
* Memory            : 32GB
* Graphics card     : Intel A770 16GB
* Graphics driver   : 
* OpenCL installed  :
* OpenCL activated  :
* Xorg              :
* Desktop           :
* GTK+              :
* gcc               :
* cflags            :
* CMAKE_BUILD_TYPE  :

**Additional context**

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by kred** [comment] 2023-12-10 10:26
[BW Across 100.zip](https://github.com/aurelienpierreeng/ansel/files/13627352/BW.Across.100.zip)

**Comment by aurelienpierre** [comment] 2023-12-12 18:06
Duplicate of #262

**Comment by aurelienpierre** [comment] 2023-12-22 02:15
Closing as duplicate. Keep following the original issue.

**Closed by aurelienpierre** 2023-12-22 02:15 UTC
Labels: duplicate
